pipeline {
  agent any
  stages {
    stage('Initial cleanup') {
      steps {
        dir(path: "${WORKSPACE}") {
          deleteDir()
        }

      }
    }

    stage('Checkout SCM') {
      steps {
        git(branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Lukobet/ansible-configm.git')
      }
    }



    stage('Run Ansible playbook') {
      steps {
        ansiblePlaybook(become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml')
      }
    }

    stage('Clean Workspace after build') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }

  }
  environment {
    ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
  }
  parameters {
    string(name: 'inventory', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration')
  }
}